# Change these first
owner: sredevopsdev # Your GitHub organization or username, where this repository lives
repo: sredevops-upptime # The name of this repository

sites:
- name: SREDevOps.org
  url: https://SREDevOps.org
- name: ElClaustro.cl 
  url: https://ElClaustro.cl
- name: SweetCaroline.cl
  url: https://SweetCaroline.cl
- name: Redacted
  url: $REDACTED_URL
  __dangerous__insecure: true
  expectedStatusCodes:
    - 401
    
commitMessages:
  commitAuthorName: "SREBot"
  commitAuthorEmail: "info@sredevops.cl"
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sredevops.org
  #  baseUrl: /sredevops-upptime
  logoUrl: https://raw.githubusercontent.com/sredevopsdev/sredevops-web/ghost/images/2023/06/ghost.svg
  name: SREDevOps.org
  introTitle: Uptime monitor and status for some of our websites
  introMessage: Powered by [**Upptime**](https://github.com/upptime/upptime)
  theme: night
  navbar:
  - title: GitHub ⎈
    href: https://github.com/$OWNER/$REPO
  - title: SREDevOps 
    href: https://sredevops.org
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: ngeorger
